spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.18.21.201:3306/nocode?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
#jpa显示sql
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

###### moyu 模块自定义参数
moyu:
  info:
    base-package: org.moyu
    version: 1.0.0
  web:
    admin-ui:
      url: http://localhost:1024
  swagger:
    title: 摸鱼开发的快速开发平台
    description: 提供管理后台、用户 App 的所有功能
    version: ${moyu.info.version}
    url: ${moyu.web.admin-ui.url}
    email: 1101734174@qq.com
    license: MIT
    license-url: https://gitee.com/zhijiantianya/ruoyi-vue-pro/blob/master/LICENSE


######### 接口文档的 配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

